name: Java CI - Regression By Tags

on: [push]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.192+12'
          distribution: 'adopt'

      - name: Run Web Tests
        if: always()
        run: mvn package -D cucumber.filter.tags="@Web"
        continue-on-error: true
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.token }}
          path: "**/functional-report.json"

      - name: Run Integration Tests
        if: always()
        run: mvn package -D cucumber.filter.tags="@Api"
        continue-on-error: true

      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.token }}
          path: "**/api-report.json"

      - name: Send Results and Generate Allure Report
        uses: Xotabu4/send-to-allure-server-action@1
        # always() needed because we want report for failed tests as well
        if: ${{ always() }}
        with:
          allure-server-url: 'http://localhost:5001/'

