on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run:  docker-compose -f /Selenoid-Hub/selenoid-environment.yml up -d

      - name: is selenoid started?
        run: curl http://localhost:4444/status

      - uses: actions/checkout@v1
      - run: mvn package
