name: Appium CI - Android
on: [ push ]

jobs:
  MacOS-Appium:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28] #22, 25,
        include:
          - EMULATOR_API: 28
            EMULATOR_ARCH: x86_64
          #- EMULATOR_API: 25
          #  EMULATOR_ARCH: x86
          #- EMULATOR_API: 22
          #  EMULATOR_ARCH: x86
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm install -g appium@v1.22.3
          appium -v
          appium &>/dev/null &
          appium -p 4444 &

      - name: Execute emulator tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2.25.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.EMULATOR_ARCH }}
          disable-animations: true
          profile: Nexus 6
          emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          #Warning: Without Tag is refers to Selenoid
          script: mvn package -DactiveProfile=jenkins -D cucumber.filter.tags="@Appium-Only"








